#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151
#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251
#define SPECIES_TREECKO 252
#define SPECIES_GROVYLE 253
#define SPECIES_SCEPTILE 254
#define SPECIES_TORCHIC 255
#define SPECIES_COMBUSKEN 256
#define SPECIES_BLAZIKEN 257
#define SPECIES_MUDKIP 258
#define SPECIES_MARSHTOMP 259
#define SPECIES_SWAMPERT 260
#define SPECIES_POOCHYENA 261
#define SPECIES_MIGHTYENA 262
#define SPECIES_ZIGZAGOON 263
#define SPECIES_LINOONE 264
#define SPECIES_WURMPLE 265
#define SPECIES_SILCOON 266
#define SPECIES_BEAUTIFLY 267
#define SPECIES_CASCOON 268
#define SPECIES_DUSTOX 269
#define SPECIES_LOTAD 270
#define SPECIES_LOMBRE 271
#define SPECIES_LUDICOLO 272
#define SPECIES_SEEDOT 273
#define SPECIES_NUZLEAF 274
#define SPECIES_SHIFTRY 275
#define SPECIES_TAILLOW 276
#define SPECIES_SWELLOW 277
#define SPECIES_WINGULL 278
#define SPECIES_PELIPPER 279
#define SPECIES_RALTS 280
#define SPECIES_KIRLIA 281
#define SPECIES_GARDEVOIR 282
#define SPECIES_SURSKIT 283
#define SPECIES_MASQUERAIN 284
#define SPECIES_SHROOMISH 285
#define SPECIES_BRELOOM 286
#define SPECIES_SLAKOTH 287
#define SPECIES_VIGOROTH 288
#define SPECIES_SLAKING 289
#define SPECIES_NINCADA 290
#define SPECIES_NINJASK 291
#define SPECIES_SHEDINJA 292
#define SPECIES_WHISMUR 293
#define SPECIES_LOUDRED 294
#define SPECIES_EXPLOUD 295
#define SPECIES_MAKUHITA 296
#define SPECIES_HARIYAMA 297
#define SPECIES_AZURILL 298
#define SPECIES_NOSEPASS 299
#define SPECIES_SKITTY 300
#define SPECIES_DELCATTY 301
#define SPECIES_SABLEYE 302
#define SPECIES_MAWILE 303
#define SPECIES_ARON 304
#define SPECIES_LAIRON 305
#define SPECIES_AGGRON 306
#define SPECIES_MEDITITE 307
#define SPECIES_MEDICHAM 308
#define SPECIES_ELECTRIKE 309
#define SPECIES_MANECTRIC 310
#define SPECIES_PLUSLE 311
#define SPECIES_MINUN 312
#define SPECIES_VOLBEAT 313
#define SPECIES_ILLUMISE 314
#define SPECIES_ROSELIA 315
#define SPECIES_GULPIN 316
#define SPECIES_SWALOT 317
#define SPECIES_CARVANHA 318
#define SPECIES_SHARPEDO 319
#define SPECIES_WAILMER 320
#define SPECIES_WAILORD 321
#define SPECIES_NUMEL 322
#define SPECIES_CAMERUPT 323
#define SPECIES_TORKOAL 324
#define SPECIES_SPOINK 325
#define SPECIES_GRUMPIG 326
#define SPECIES_SPINDA 327
#define SPECIES_TRAPINCH 328
#define SPECIES_VIBRAVA 329
#define SPECIES_FLYGON 330
#define SPECIES_CACNEA 331
#define SPECIES_CACTURNE 332
#define SPECIES_SWABLU 333
#define SPECIES_ALTARIA 334
#define SPECIES_ZANGOOSE 335
#define SPECIES_SEVIPER 336
#define SPECIES_LUNATONE 337
#define SPECIES_SOLROCK 338
#define SPECIES_BARBOACH 339
#define SPECIES_WHISCASH 340
#define SPECIES_CORPHISH 341
#define SPECIES_CRAWDAUNT 342
#define SPECIES_BALTOY 343
#define SPECIES_CLAYDOL 344
#define SPECIES_LILEEP 345
#define SPECIES_CRADILY 346
#define SPECIES_ANORITH 347
#define SPECIES_ARMALDO 348
#define SPECIES_FEEBAS 349
#define SPECIES_MILOTIC 350
#define SPECIES_CASTFORM 351
#define SPECIES_KECLEON 352
#define SPECIES_SHUPPET 353
#define SPECIES_BANETTE 354
#define SPECIES_DUSKULL 355
#define SPECIES_DUSCLOPS 356
#define SPECIES_TROPIUS 357
#define SPECIES_CHIMECHO 358
#define SPECIES_ABSOL 359
#define SPECIES_WYNAUT 360
#define SPECIES_SNORUNT 361
#define SPECIES_GLALIE 362
#define SPECIES_SPHEAL 363
#define SPECIES_SEALEO 364
#define SPECIES_WALREIN 365
#define SPECIES_CLAMPERL 366
#define SPECIES_HUNTAIL 367
#define SPECIES_GOREBYSS 368
#define SPECIES_RELICANTH 369
#define SPECIES_LUVDISC 370
#define SPECIES_BAGON 371
#define SPECIES_SHELGON 372
#define SPECIES_SALAMENCE 373
#define SPECIES_BELDUM 374
#define SPECIES_METANG 375
#define SPECIES_METAGROSS 376
#define SPECIES_REGIROCK 377
#define SPECIES_REGICE 378
#define SPECIES_REGISTEEL 379
#define SPECIES_LATIAS 380
#define SPECIES_LATIOS 381
#define SPECIES_KYOGRE 382
#define SPECIES_GROUDON 383
#define SPECIES_RAYQUAZA 384
#define SPECIES_JIRACHI 385
#define SPECIES_DEOXYS 386
#define SPECIES_BUDEW 387
#define SPECIES_ROSERADE 388
#define SPECIES_AMBIPOM 389
#define SPECIES_BONSLY 390
#define SPECIES_MIME_JR 391
#define SPECIES_HAPPINY 392
#define SPECIES_MUNCHLAX 393
#define SPECIES_MISMAGIUS 394
#define SPECIES_HONCHKROW 395
#define SPECIES_CHINGLING 396
#define SPECIES_MANTYKE 397
#define SPECIES_WEAVILE 398
#define SPECIES_MAGNEZONE 399
#define SPECIES_LICKILICKY 400
#define SPECIES_RHYPERIOR 401
#define SPECIES_TANGROWTH 402
#define SPECIES_ELECTIVIRE 403
#define SPECIES_MAGMORTAR 404
#define SPECIES_TOGEKISS 405
#define SPECIES_YANMEGA 406
#define SPECIES_LEAFEON 407
#define SPECIES_GLACEON 408
#define SPECIES_GLISCOR 409
#define SPECIES_MAMOSWINE 410
#define SPECIES_PORYGON_Z 411
#define SPECIES_GALLADE 412
#define SPECIES_PROBOPASS 413
#define SPECIES_DUSKNOIR 414
#define SPECIES_FROSLASS 415
#define SPECIES_REGIGIGAS 416
#define SPECIES_SYLVEON 417
#define SPECIES_QUAXLY 418
#define SPECIES_FUECOCO 419
#define SPECIES_SPRIGATITO 420

//Unused Expansion Species
#define GEN_4_SPECIES SPECIES_SPRIGATITO

#define SPECIES_TURTWIG 		GEN_4_SPECIES + 1
#define SPECIES_GROTLE 			GEN_4_SPECIES + 2
#define SPECIES_TORTERRA 		GEN_4_SPECIES + 3
#define SPECIES_CHIMCHAR 		GEN_4_SPECIES + 4
#define SPECIES_MONFERNO 		GEN_4_SPECIES + 5
#define SPECIES_INFERNAPE 		GEN_4_SPECIES + 6
#define SPECIES_PIPLUP 			GEN_4_SPECIES + 7
#define SPECIES_PRINPLUP 		GEN_4_SPECIES + 8
#define SPECIES_EMPOLEON 		GEN_4_SPECIES + 9
#define SPECIES_STARLY 			GEN_4_SPECIES + 10
#define SPECIES_STARAVIA 		GEN_4_SPECIES + 11
#define SPECIES_STARAPTOR 		GEN_4_SPECIES + 12
#define SPECIES_BIDOOF 			GEN_4_SPECIES + 13
#define SPECIES_BIBAREL 		GEN_4_SPECIES + 14
#define SPECIES_KRICKETOT 		GEN_4_SPECIES + 15
#define SPECIES_KRICKETUNE 		GEN_4_SPECIES + 16
#define SPECIES_SHINX 			GEN_4_SPECIES + 17
#define SPECIES_LUXIO 			GEN_4_SPECIES + 18
#define SPECIES_LUXRAY 			GEN_4_SPECIES + 19
#define SPECIES_CRANIDOS 		GEN_4_SPECIES + 20
#define SPECIES_RAMPARDOS 		GEN_4_SPECIES + 21
#define SPECIES_SHIELDON 		GEN_4_SPECIES + 22
#define SPECIES_BASTIODON 		GEN_4_SPECIES + 23
#define SPECIES_BURMY 			GEN_4_SPECIES + 24
#define SPECIES_WORMADAM 		GEN_4_SPECIES + 25
#define SPECIES_MOTHIM 			GEN_4_SPECIES + 26
#define SPECIES_COMBEE 			GEN_4_SPECIES + 27
#define SPECIES_VESPIQUEN 		GEN_4_SPECIES + 28
#define SPECIES_PACHIRISU 		GEN_4_SPECIES + 29
#define SPECIES_BUIZEL 			GEN_4_SPECIES + 30
#define SPECIES_FLOATZEL 		GEN_4_SPECIES + 31
#define SPECIES_CHERUBI 		GEN_4_SPECIES + 32
#define SPECIES_CHERRIM 		GEN_4_SPECIES + 33
#define SPECIES_SHELLOS 		GEN_4_SPECIES + 34
#define SPECIES_GASTRODON 		GEN_4_SPECIES + 35
#define SPECIES_DRIFLOON 		GEN_4_SPECIES + 36
#define SPECIES_DRIFBLIM 		GEN_4_SPECIES + 37
#define SPECIES_BUNEARY 		GEN_4_SPECIES + 38
#define SPECIES_LOPUNNY 		GEN_4_SPECIES + 39
#define SPECIES_GLAMEOW 		GEN_4_SPECIES + 40
#define SPECIES_PURUGLY 		GEN_4_SPECIES + 41
#define SPECIES_STUNKY 			GEN_4_SPECIES + 42
#define SPECIES_SKUNTANK 		GEN_4_SPECIES + 43
#define SPECIES_BRONZOR 		GEN_4_SPECIES + 44
#define SPECIES_BRONZONG 		GEN_4_SPECIES + 45
#define SPECIES_CHATOT 			GEN_4_SPECIES + 46
#define SPECIES_SPIRITOMB 		GEN_4_SPECIES + 47
#define SPECIES_GIBLE 			GEN_4_SPECIES + 48
#define SPECIES_GABITE 			GEN_4_SPECIES + 49
#define SPECIES_GARCHOMP 		GEN_4_SPECIES + 50
#define SPECIES_RIOLU 			GEN_4_SPECIES + 51
#define SPECIES_LUCARIO 		GEN_4_SPECIES + 52
#define SPECIES_HIPPOPOTAS 		GEN_4_SPECIES + 53
#define SPECIES_HIPPOWDON 		GEN_4_SPECIES + 54
#define SPECIES_SKORUPI 		GEN_4_SPECIES + 55
#define SPECIES_DRAPION 		GEN_4_SPECIES + 56
#define SPECIES_CROAGUNK 		GEN_4_SPECIES + 57
#define SPECIES_TOXICROAK 		GEN_4_SPECIES + 58
#define SPECIES_CARNIVINE 		GEN_4_SPECIES + 59
#define SPECIES_FINNEON 		GEN_4_SPECIES + 60
#define SPECIES_LUMINEON 		GEN_4_SPECIES + 61
#define SPECIES_SNOVER 			GEN_4_SPECIES + 62
#define SPECIES_ABOMASNOW 		GEN_4_SPECIES + 63
#define SPECIES_ROTOM 			GEN_4_SPECIES + 64
#define SPECIES_UXIE 			GEN_4_SPECIES + 65
#define SPECIES_MESPRIT 		GEN_4_SPECIES + 66
#define SPECIES_AZELF 			GEN_4_SPECIES + 67
#define SPECIES_DIALGA 			GEN_4_SPECIES + 68
#define SPECIES_PALKIA 			GEN_4_SPECIES + 69
#define SPECIES_HEATRAN 		GEN_4_SPECIES + 70
#define SPECIES_GIRATINA 		GEN_4_SPECIES + 71
#define SPECIES_CRESSELIA 		GEN_4_SPECIES + 72
#define SPECIES_PHIONE 			GEN_4_SPECIES + 73
#define SPECIES_MANAPHY 		GEN_4_SPECIES + 74
#define SPECIES_DARKRAI 		GEN_4_SPECIES + 75
#define SPECIES_SHAYMIN 		GEN_4_SPECIES + 76
#define SPECIES_ARCEUS 			GEN_4_SPECIES + 77

#define GEN_5_SPECIES 			SPECIES_ARCEUS

#define SPECIES_VICTINI 		GEN_5_SPECIES + 1
#define SPECIES_SNIVY 			GEN_5_SPECIES + 2
#define SPECIES_SERVINE 		GEN_5_SPECIES + 3
#define SPECIES_SERPERIOR  		GEN_5_SPECIES + 4
#define SPECIES_TEPIG 			GEN_5_SPECIES + 5
#define SPECIES_PIGNITE 		GEN_5_SPECIES + 6
#define SPECIES_EMBOAR 			GEN_5_SPECIES + 7
#define SPECIES_OSHAWOTT 		GEN_5_SPECIES + 8
#define SPECIES_DEWOTT 			GEN_5_SPECIES + 9
#define SPECIES_SAMUROTT 		GEN_5_SPECIES + 10
#define SPECIES_PATRAT 			GEN_5_SPECIES + 11
#define SPECIES_WATCHOG 		GEN_5_SPECIES + 12
#define SPECIES_LILLIPUP 		GEN_5_SPECIES + 13
#define SPECIES_HERDIER 		GEN_5_SPECIES + 14
#define SPECIES_STOUTLAND 		GEN_5_SPECIES + 15
#define SPECIES_PURRLOIN 		GEN_5_SPECIES + 16
#define SPECIES_LIEPARD 		GEN_5_SPECIES + 17
#define SPECIES_PANSAGE 		GEN_5_SPECIES + 18
#define SPECIES_SIMISAGE 		GEN_5_SPECIES + 19
#define SPECIES_PANSEAR 		GEN_5_SPECIES + 20
#define SPECIES_SIMISEAR 		GEN_5_SPECIES + 21
#define SPECIES_PANPOUR 		GEN_5_SPECIES + 22
#define SPECIES_SIMIPOUR 		GEN_5_SPECIES + 23
#define SPECIES_MUNNA 			GEN_5_SPECIES + 24
#define SPECIES_MUSHARNA 		GEN_5_SPECIES + 25
#define SPECIES_PIDOVE 			GEN_5_SPECIES + 26
#define SPECIES_TRANQUILL 		GEN_5_SPECIES + 27
#define SPECIES_UNFEZANT 		GEN_5_SPECIES + 28
#define SPECIES_BLITZLE 		GEN_5_SPECIES + 29
#define SPECIES_ZEBSTRIKA 		GEN_5_SPECIES + 30
#define SPECIES_ROGGENROLA 		GEN_5_SPECIES + 31
#define SPECIES_BOLDORE 		GEN_5_SPECIES + 32
#define SPECIES_GIGALITH 		GEN_5_SPECIES + 33
#define SPECIES_WOOBAT 			GEN_5_SPECIES + 34
#define SPECIES_SWOOBAT 		GEN_5_SPECIES + 35
#define SPECIES_DRILBUR 		GEN_5_SPECIES + 36
#define SPECIES_EXCADRILL 		GEN_5_SPECIES + 37
#define SPECIES_AUDINO 			GEN_5_SPECIES + 38
#define SPECIES_TIMBURR 		GEN_5_SPECIES + 39
#define SPECIES_GURDURR 		GEN_5_SPECIES + 40
#define SPECIES_CONKELDURR 		GEN_5_SPECIES + 41
#define SPECIES_TYMPOLE 		GEN_5_SPECIES + 42
#define SPECIES_PALPITOAD 		GEN_5_SPECIES + 43
#define SPECIES_SEISMITOAD 		GEN_5_SPECIES + 44
#define SPECIES_THROH 			GEN_5_SPECIES + 45
#define SPECIES_SAWK 			GEN_5_SPECIES + 46
#define SPECIES_SEWADDLE 		GEN_5_SPECIES + 47
#define SPECIES_SWADLOON 		GEN_5_SPECIES + 48
#define SPECIES_LEAVANNY 		GEN_5_SPECIES + 49
#define SPECIES_VENIPEDE 		GEN_5_SPECIES + 50
#define SPECIES_WHIRLIPEDE 		GEN_5_SPECIES + 51
#define SPECIES_SCOLIPEDE 		GEN_5_SPECIES + 52
#define SPECIES_COTTONEE 		GEN_5_SPECIES + 53
#define SPECIES_WHIMSICOTT 		GEN_5_SPECIES + 54
#define SPECIES_PETILIL 		GEN_5_SPECIES + 55
#define SPECIES_LILLIGANT 		GEN_5_SPECIES + 56
#define SPECIES_BASCULIN 		GEN_5_SPECIES + 57
#define SPECIES_SANDILE 		GEN_5_SPECIES + 58
#define SPECIES_KROKOROK 		GEN_5_SPECIES + 59
#define SPECIES_KROOKODILE 		GEN_5_SPECIES + 60
#define SPECIES_DARUMAKA 		GEN_5_SPECIES + 61
#define SPECIES_DARMANITAN 		GEN_5_SPECIES + 62
#define SPECIES_MARACTUS 		GEN_5_SPECIES + 63
#define SPECIES_DWEBBLE 		GEN_5_SPECIES + 64
#define SPECIES_CRUSTLE 		GEN_5_SPECIES + 65
#define SPECIES_SCRAGGY 		GEN_5_SPECIES + 66
#define SPECIES_SCRAFTY 		GEN_5_SPECIES + 67
#define SPECIES_SIGILYPH 		GEN_5_SPECIES + 68
#define SPECIES_YAMASK 			GEN_5_SPECIES + 69
#define SPECIES_COFAGRIGUS  	GEN_5_SPECIES + 70
#define SPECIES_TIRTOUGA 		GEN_5_SPECIES + 71
#define SPECIES_CARRACOSTA 		GEN_5_SPECIES + 72
#define SPECIES_ARCHEN 			GEN_5_SPECIES + 73
#define SPECIES_ARCHEOPS 		GEN_5_SPECIES + 74
#define SPECIES_TRUBBISH 		GEN_5_SPECIES + 75
#define SPECIES_GARBODOR 		GEN_5_SPECIES + 76
#define SPECIES_ZORUA 			GEN_5_SPECIES + 77
#define SPECIES_ZOROARK 		GEN_5_SPECIES + 78
#define SPECIES_MINCCINO 		GEN_5_SPECIES + 79
#define SPECIES_CINCCINO 		GEN_5_SPECIES + 80
#define SPECIES_GOTHITA 		GEN_5_SPECIES + 81
#define SPECIES_GOTHORITA  		GEN_5_SPECIES + 82
#define SPECIES_GOTHITELLE  	GEN_5_SPECIES + 83
#define SPECIES_SOLOSIS  		GEN_5_SPECIES + 84
#define SPECIES_DUOSION  		GEN_5_SPECIES + 85
#define SPECIES_REUNICLUS  		GEN_5_SPECIES + 86
#define SPECIES_DUCKLETT  		GEN_5_SPECIES + 87
#define SPECIES_SWANNA  		GEN_5_SPECIES + 88
#define SPECIES_VANILLITE  		GEN_5_SPECIES + 89
#define SPECIES_VANILLISH  		GEN_5_SPECIES + 90
#define SPECIES_VANILLUXE  		GEN_5_SPECIES + 91
#define SPECIES_DEERLING  		GEN_5_SPECIES + 92
#define SPECIES_SAWSBUCK  		GEN_5_SPECIES + 93
#define SPECIES_EMOLGA  		GEN_5_SPECIES + 94
#define SPECIES_KARRABLAST  	GEN_5_SPECIES + 95
#define SPECIES_ESCAVALIER  	GEN_5_SPECIES + 96
#define SPECIES_FOONGUS  		GEN_5_SPECIES + 97
#define SPECIES_AMOONGUSS  		GEN_5_SPECIES + 98
#define SPECIES_FRILLISH  		GEN_5_SPECIES + 99
#define SPECIES_JELLICENT  		GEN_5_SPECIES + 100
#define SPECIES_ALOMOMOLA  		GEN_5_SPECIES + 101
#define SPECIES_JOLTIK  		GEN_5_SPECIES + 102
#define SPECIES_GALVANTULA  	GEN_5_SPECIES + 103
#define SPECIES_FERROSEED  		GEN_5_SPECIES + 104
#define SPECIES_FERROTHORN  	GEN_5_SPECIES + 105
#define SPECIES_KLINK  			GEN_5_SPECIES + 106
#define SPECIES_KLANG  			GEN_5_SPECIES + 107
#define SPECIES_KLINKLANG  		GEN_5_SPECIES + 108
#define SPECIES_TYNAMO  		GEN_5_SPECIES + 109
#define SPECIES_EELEKTRIK  		GEN_5_SPECIES + 110
#define SPECIES_EELEKTROSS 		GEN_5_SPECIES + 112
#define SPECIES_ELGYEM  		GEN_5_SPECIES + 113
#define SPECIES_BEHEEYEM  		GEN_5_SPECIES + 114
#define SPECIES_LITWICK  		GEN_5_SPECIES + 115
#define SPECIES_LAMPENT  		GEN_5_SPECIES + 116
#define SPECIES_CHANDELURE  	GEN_5_SPECIES + 117
#define SPECIES_AXEW  			GEN_5_SPECIES + 118
#define SPECIES_FRAXURE  		GEN_5_SPECIES + 119
#define SPECIES_HAXORUS  		GEN_5_SPECIES + 120
#define SPECIES_CUBCHOO  		GEN_5_SPECIES + 121
#define SPECIES_BEARTIC  		GEN_5_SPECIES + 122
#define SPECIES_CRYOGONAL  		GEN_5_SPECIES + 123
#define SPECIES_SHELMET  		GEN_5_SPECIES + 124
#define SPECIES_ACCELGOR  		GEN_5_SPECIES + 125
#define SPECIES_STUNFISK  		GEN_5_SPECIES + 126
#define SPECIES_MIENFOO  		GEN_5_SPECIES + 127
#define SPECIES_MIENSHAO  		GEN_5_SPECIES + 128
#define SPECIES_DRUDDIGON  		GEN_5_SPECIES + 129
#define SPECIES_GOLETT  		GEN_5_SPECIES + 130
#define SPECIES_GOLURK  		GEN_5_SPECIES + 131
#define SPECIES_PAWNIARD  		GEN_5_SPECIES + 132
#define SPECIES_BISHARP  		GEN_5_SPECIES + 133
#define SPECIES_BOUFFALANT  	GEN_5_SPECIES + 134
#define SPECIES_RUFFLET  		GEN_5_SPECIES + 135
#define SPECIES_BRAVIARY  		GEN_5_SPECIES + 136
#define SPECIES_VULLABY  		GEN_5_SPECIES + 137
#define SPECIES_MANDIBUZZ  		GEN_5_SPECIES + 138
#define SPECIES_HEATMOR  		GEN_5_SPECIES + 139
#define SPECIES_DURANT  		GEN_5_SPECIES + 140
#define SPECIES_DEINO  			GEN_5_SPECIES + 141
#define SPECIES_ZWEILOUS  		GEN_5_SPECIES + 142
#define SPECIES_HYDREIGON  		GEN_5_SPECIES + 143
#define SPECIES_LARVESTA  		GEN_5_SPECIES + 144
#define SPECIES_VOLCARONA  		GEN_5_SPECIES + 145
#define SPECIES_COBALION  		GEN_5_SPECIES + 146
#define SPECIES_TERRAKION  		GEN_5_SPECIES + 147
#define SPECIES_VIRIZION  		GEN_5_SPECIES + 148
#define SPECIES_TORNADUS  		GEN_5_SPECIES + 149
#define SPECIES_THUNDURUS  		GEN_5_SPECIES + 150
#define SPECIES_RESHIRAM  		GEN_5_SPECIES + 151
#define SPECIES_ZEKROM  		GEN_5_SPECIES + 152
#define SPECIES_LANDORUS  		GEN_5_SPECIES + 153
#define SPECIES_KYUREM  		GEN_5_SPECIES + 154
#define SPECIES_KELDEO  		GEN_5_SPECIES + 155
#define SPECIES_MELOETTA  		GEN_5_SPECIES + 156
#define SPECIES_GENESECT  		GEN_5_SPECIES + 157

#define GEN_6_SPECIES			SPECIES_GENESECT

#define SPECIES_CHESPIN 		GEN_6_SPECIES + 1
#define SPECIES_QUILLADIN 		GEN_6_SPECIES + 2
#define SPECIES_CHESNAUGHT 		GEN_6_SPECIES + 3
#define SPECIES_FENNEKIN 		GEN_6_SPECIES + 4
#define SPECIES_BRAIXEN 		GEN_6_SPECIES + 5
#define SPECIES_DELPHOX 		GEN_6_SPECIES + 6
#define SPECIES_FROAKIE 		GEN_6_SPECIES + 7
#define SPECIES_FROGADIER 		GEN_6_SPECIES + 8
#define SPECIES_GRENINJA 		GEN_6_SPECIES + 9
#define SPECIES_BUNNELBY 		GEN_6_SPECIES + 10
#define SPECIES_DIGGERSBY 		GEN_6_SPECIES + 11
#define SPECIES_FLETCHLING 		GEN_6_SPECIES + 12
#define SPECIES_FLETCHINDER 	GEN_6_SPECIES + 13
#define SPECIES_TALONFLAME 		GEN_6_SPECIES + 14
#define SPECIES_SCATTERBUG 		GEN_6_SPECIES + 15
#define SPECIES_SPEWPA 			GEN_6_SPECIES + 16
#define SPECIES_VIVILLON 		GEN_6_SPECIES + 17 // Icy Snow Pattern
#define SPECIES_LITLEO 			GEN_6_SPECIES + 18
#define SPECIES_PYROAR 			GEN_6_SPECIES + 19
#define SPECIES_FLABEBE 		GEN_6_SPECIES + 20 // Red Flower
#define SPECIES_FLOETTE 		GEN_6_SPECIES + 21
#define SPECIES_FLORGES 		GEN_6_SPECIES + 22
#define SPECIES_SKIDDO 			GEN_6_SPECIES + 23
#define SPECIES_GOGOAT 			GEN_6_SPECIES + 24
#define SPECIES_PANCHAM 		GEN_6_SPECIES + 25
#define SPECIES_PANGORO 		GEN_6_SPECIES + 26
#define SPECIES_FURFROU 		GEN_6_SPECIES + 27
#define SPECIES_ESPURR 			GEN_6_SPECIES + 28
#define SPECIES_MEOWSTIC 		GEN_6_SPECIES + 29
#define SPECIES_HONEDGE 		GEN_6_SPECIES + 30
#define SPECIES_DOUBLADE 		GEN_6_SPECIES + 31
#define SPECIES_AEGISLASH 		GEN_6_SPECIES + 32
#define SPECIES_SPRITZEE 		GEN_6_SPECIES + 33
#define SPECIES_AROMATISSE 		GEN_6_SPECIES + 34
#define SPECIES_SWIRLIX 		GEN_6_SPECIES + 35
#define SPECIES_SLURPUFF 		GEN_6_SPECIES + 36
#define SPECIES_INKAY 			GEN_6_SPECIES + 37
#define SPECIES_MALAMAR 		GEN_6_SPECIES + 38
#define SPECIES_BINACLE 		GEN_6_SPECIES + 39
#define SPECIES_BARBARACLE 		GEN_6_SPECIES + 40
#define SPECIES_SKRELP 			GEN_6_SPECIES + 41
#define SPECIES_DRAGALGE 		GEN_6_SPECIES + 42
#define SPECIES_CLAUNCHER 		GEN_6_SPECIES + 43
#define SPECIES_CLAWITZER 		GEN_6_SPECIES + 44
#define SPECIES_HELIOPTILE 		GEN_6_SPECIES + 45
#define SPECIES_HELIOLISK 		GEN_6_SPECIES + 46
#define SPECIES_TYRUNT 			GEN_6_SPECIES + 47
#define SPECIES_TYRANTRUM 		GEN_6_SPECIES + 48
#define SPECIES_AMAURA 			GEN_6_SPECIES + 49
#define SPECIES_AURORUS 		GEN_6_SPECIES + 50
#define SPECIES_HAWLUCHA 		GEN_6_SPECIES + 51
#define SPECIES_DEDENNE 		GEN_6_SPECIES + 52
#define SPECIES_CARBINK 		GEN_6_SPECIES + 53
#define SPECIES_GOOMY 			GEN_6_SPECIES + 54
#define SPECIES_SLIGGOO 		GEN_6_SPECIES + 55
#define SPECIES_GOODRA 			GEN_6_SPECIES + 56
#define SPECIES_KLEFKI 			GEN_6_SPECIES + 57
#define SPECIES_PHANTUMP 		GEN_6_SPECIES + 58
#define SPECIES_TREVENANT 		GEN_6_SPECIES + 59
#define SPECIES_PUMPKABOO 		GEN_6_SPECIES + 60
#define SPECIES_GOURGEIST 		GEN_6_SPECIES + 61
#define SPECIES_BERGMITE 		GEN_6_SPECIES + 62
#define SPECIES_AVALUGG 		GEN_6_SPECIES + 63
#define SPECIES_NOIBAT 			GEN_6_SPECIES + 64
#define SPECIES_NOIVERN 		GEN_6_SPECIES + 65
#define SPECIES_XERNEAS 		GEN_6_SPECIES + 66
#define SPECIES_YVELTAL 		GEN_6_SPECIES + 67
#define SPECIES_ZYGARDE 		GEN_6_SPECIES + 68
#define SPECIES_DIANCIE 		GEN_6_SPECIES + 69
#define SPECIES_HOOPA 			GEN_6_SPECIES + 70
#define SPECIES_VOLCANION 		GEN_6_SPECIES + 71

#define GEN_7_SPECIES			SPECIES_VOLCANION

#define SPECIES_ROWLET 			GEN_7_SPECIES + 1
#define SPECIES_DARTRIX 		GEN_7_SPECIES + 2
#define SPECIES_DECIDUEYE 		GEN_7_SPECIES + 3
#define SPECIES_LITTEN  		GEN_7_SPECIES + 4
#define SPECIES_TORRACAT  		GEN_7_SPECIES + 5
#define SPECIES_INCINEROAR		GEN_7_SPECIES + 6
#define SPECIES_POPPLIO			GEN_7_SPECIES + 7
#define SPECIES_BRIONNE			GEN_7_SPECIES + 8
#define SPECIES_PRIMARINA 		GEN_7_SPECIES + 9
#define SPECIES_PIKIPEK 		GEN_7_SPECIES + 10
#define SPECIES_TRUMBEAK 		GEN_7_SPECIES + 11
#define SPECIES_TOUCANNON 		GEN_7_SPECIES + 12
#define SPECIES_YUNGOOS 		GEN_7_SPECIES + 13
#define SPECIES_GUMSHOOS 		GEN_7_SPECIES + 14
#define SPECIES_GRUBBIN 		GEN_7_SPECIES + 15
#define SPECIES_CHARJABUG 		GEN_7_SPECIES + 16
#define SPECIES_VIKAVOLT 		GEN_7_SPECIES + 17
#define SPECIES_CRABRAWLER 		GEN_7_SPECIES + 18
#define SPECIES_CRABOMINABLE 	GEN_7_SPECIES + 19
#define SPECIES_ORICORIO 		GEN_7_SPECIES + 20
#define SPECIES_CUTIEFLY 		GEN_7_SPECIES + 21
#define SPECIES_RIBOMBEE 		GEN_7_SPECIES + 22
#define SPECIES_ROCKRUFF 		GEN_7_SPECIES + 23
#define SPECIES_LYCANROC 		GEN_7_SPECIES + 24
#define SPECIES_WISHIWASHI 		GEN_7_SPECIES + 25
#define SPECIES_MAREANIE 		GEN_7_SPECIES + 26
#define SPECIES_TOXAPEX 		GEN_7_SPECIES + 27
#define SPECIES_MUDBRAY 		GEN_7_SPECIES + 28
#define SPECIES_MUDSDALE 		GEN_7_SPECIES + 29
#define SPECIES_DEWPIDER 		GEN_7_SPECIES + 30
#define SPECIES_ARAQUANID 		GEN_7_SPECIES + 31
#define SPECIES_FOMANTIS 		GEN_7_SPECIES + 32
#define SPECIES_LURANTIS 		GEN_7_SPECIES + 33
#define SPECIES_MORELULL 		GEN_7_SPECIES + 34
#define SPECIES_SHIINOTIC 		GEN_7_SPECIES + 35
#define SPECIES_SALANDIT 		GEN_7_SPECIES + 36
#define SPECIES_SALAZZLE 		GEN_7_SPECIES + 37
#define SPECIES_STUFFUL 		GEN_7_SPECIES + 38
#define SPECIES_BEWEAR 			GEN_7_SPECIES + 39
#define SPECIES_BOUNSWEET 		GEN_7_SPECIES + 40
#define SPECIES_STEENEE 		GEN_7_SPECIES + 41
#define SPECIES_TSAREENA 		GEN_7_SPECIES + 42
#define SPECIES_COMFEY 			GEN_7_SPECIES + 43
#define SPECIES_ORANGURU 		GEN_7_SPECIES + 44
#define SPECIES_PASSIMIAN 		GEN_7_SPECIES + 45
#define SPECIES_WIMPOD 			GEN_7_SPECIES + 46
#define SPECIES_GOLISOPOD 		GEN_7_SPECIES + 47
#define SPECIES_SANDYGAST 		GEN_7_SPECIES + 48
#define SPECIES_PALOSSAND 		GEN_7_SPECIES + 49
#define SPECIES_PYUKUMUKU 		GEN_7_SPECIES + 50
#define SPECIES_TYPE_NULL 		GEN_7_SPECIES + 51
#define SPECIES_SILVALLY 		GEN_7_SPECIES + 52
#define SPECIES_MINIOR 			GEN_7_SPECIES + 53
#define SPECIES_KOMALA 			GEN_7_SPECIES + 54
#define SPECIES_TURTONATOR 		GEN_7_SPECIES + 55
#define SPECIES_TOGEDEMARU 		GEN_7_SPECIES + 56
#define SPECIES_MIMIKYU 		GEN_7_SPECIES + 57
#define SPECIES_BRUXISH 		GEN_7_SPECIES + 58
#define SPECIES_DRAMPA 			GEN_7_SPECIES + 59
#define SPECIES_DHELMISE 		GEN_7_SPECIES + 60
#define SPECIES_JANGMO_O 		GEN_7_SPECIES + 61
#define SPECIES_HAKAMO_O 		GEN_7_SPECIES + 62
#define SPECIES_KOMMO_O 		GEN_7_SPECIES + 63
#define SPECIES_TAPU_KOKO 		GEN_7_SPECIES + 64
#define SPECIES_TAPU_LELE 		GEN_7_SPECIES + 65
#define SPECIES_TAPU_BULU 		GEN_7_SPECIES + 66
#define SPECIES_TAPU_FINI 		GEN_7_SPECIES + 67
#define SPECIES_COSMOG 			GEN_7_SPECIES + 68
#define SPECIES_COSMOEM 		GEN_7_SPECIES + 69
#define SPECIES_SOLGALEO 		GEN_7_SPECIES + 70
#define SPECIES_LUNALA 			GEN_7_SPECIES + 71
#define SPECIES_NIHILEGO 		GEN_7_SPECIES + 72
#define SPECIES_BUZZWOLE 		GEN_7_SPECIES + 73
#define SPECIES_PHEROMOSA 		GEN_7_SPECIES + 74
#define SPECIES_XURKITREE 		GEN_7_SPECIES + 75
#define SPECIES_CELESTEELA 		GEN_7_SPECIES + 76
#define SPECIES_KARTANA 		GEN_7_SPECIES + 77
#define SPECIES_GUZZLORD 		GEN_7_SPECIES + 78
#define SPECIES_NECROZMA 		GEN_7_SPECIES + 79
#define SPECIES_MAGEARNA 		GEN_7_SPECIES + 80
#define SPECIES_MARSHADOW 		GEN_7_SPECIES + 81
#define SPECIES_POIPOLE 		GEN_7_SPECIES + 82
#define SPECIES_NAGANADEL 		GEN_7_SPECIES + 83
#define SPECIES_STAKATAKA 		GEN_7_SPECIES + 84
#define SPECIES_BLACEPHALON 	GEN_7_SPECIES + 85
#define SPECIES_ZERAORA 		GEN_7_SPECIES + 86
#define SPECIES_MELTAN 			GEN_7_SPECIES + 87
#define SPECIES_MELMETAL 		GEN_7_SPECIES + 88

#define GEN_8_SPECIES			SPECIES_MELMETAL

#define SPECIES_GROOKEY 		GEN_8_SPECIES + 1
#define SPECIES_THWACKEY 		GEN_8_SPECIES + 2
#define SPECIES_RILLABOOM 		GEN_8_SPECIES + 3
#define SPECIES_SCORBUNNY 		GEN_8_SPECIES + 4
#define SPECIES_RABOOT 			GEN_8_SPECIES + 5
#define SPECIES_CINDERACE 		GEN_8_SPECIES + 6
#define SPECIES_SOBBLE 			GEN_8_SPECIES + 7
#define SPECIES_DRIZZILE		GEN_8_SPECIES + 8
#define SPECIES_INTELEON		GEN_8_SPECIES + 9
#define SPECIES_SKWOVET			GEN_8_SPECIES + 10
#define SPECIES_GREEDENT		GEN_8_SPECIES + 11
#define SPECIES_ROOKIDEE		GEN_8_SPECIES + 12
#define SPECIES_CORVISQUIRE		GEN_8_SPECIES + 13
#define SPECIES_CORVIKNIGHT		GEN_8_SPECIES + 14
#define SPECIES_BLIPBUG			GEN_8_SPECIES + 15
#define SPECIES_DOTTLER			GEN_8_SPECIES + 16
#define SPECIES_ORBEETLE		GEN_8_SPECIES + 17
#define SPECIES_NICKIT			GEN_8_SPECIES + 18
#define SPECIES_THIEVUL			GEN_8_SPECIES + 19
#define SPECIES_GOSSIFLEUR		GEN_8_SPECIES + 20
#define SPECIES_ELDEGOSS		GEN_8_SPECIES + 21
#define SPECIES_WOOLOO			GEN_8_SPECIES + 22
#define SPECIES_DUBWOOL			GEN_8_SPECIES + 23
#define SPECIES_CHEWTLE			GEN_8_SPECIES + 24
#define SPECIES_DREDNAW 		GEN_8_SPECIES + 25
#define SPECIES_YAMPER 			GEN_8_SPECIES + 26
#define SPECIES_BOLTUND 		GEN_8_SPECIES + 27
#define SPECIES_ROLYCOLY 		GEN_8_SPECIES + 28
#define SPECIES_CARKOL 			GEN_8_SPECIES + 29
#define SPECIES_COALOSSAL 		GEN_8_SPECIES + 30
#define SPECIES_APPLIN 			GEN_8_SPECIES + 31
#define SPECIES_FLAPPLE 		GEN_8_SPECIES + 32
#define SPECIES_APPLETUN 		GEN_8_SPECIES + 33
#define SPECIES_SILICOBRA 		GEN_8_SPECIES + 34
#define SPECIES_SANDACONDA 		GEN_8_SPECIES + 35
#define SPECIES_CRAMORANT 		GEN_8_SPECIES + 36
#define SPECIES_ARROKUDA 		GEN_8_SPECIES + 37
#define SPECIES_BARRASKEWDA 	GEN_8_SPECIES + 38
#define SPECIES_TOXEL 			GEN_8_SPECIES + 39
#define SPECIES_TOXTRICITY 		GEN_8_SPECIES + 40
#define SPECIES_SIZZLIPEDE 		GEN_8_SPECIES + 41
#define SPECIES_CENTISKORCH 	GEN_8_SPECIES + 42
#define SPECIES_CLOBBOPUS 		GEN_8_SPECIES + 43
#define SPECIES_GRAPPLOCT 		GEN_8_SPECIES + 44
#define SPECIES_SINISTEA 		GEN_8_SPECIES + 45
#define SPECIES_POLTEAGEIST 	GEN_8_SPECIES + 46
#define SPECIES_HATENNA 		GEN_8_SPECIES + 47
#define SPECIES_HATTREM 		GEN_8_SPECIES + 48
#define SPECIES_HATTERENE 		GEN_8_SPECIES + 49
#define SPECIES_IMPIDIMP 		GEN_8_SPECIES + 50
#define SPECIES_MORGREM 		GEN_8_SPECIES + 51
#define SPECIES_GRIMMSNARL 		GEN_8_SPECIES + 52
#define SPECIES_OBSTAGOON 		GEN_8_SPECIES + 53
#define SPECIES_PERRSERKER 		GEN_8_SPECIES + 54
#define SPECIES_CURSOLA 		GEN_8_SPECIES + 55
#define SPECIES_SIRFETCHD 		GEN_8_SPECIES + 56
#define SPECIES_MR_RIME 		GEN_8_SPECIES + 57
#define SPECIES_RUNERIGUS 		GEN_8_SPECIES + 58
#define SPECIES_MILCERY 		GEN_8_SPECIES + 59
#define SPECIES_ALCREMIE 		GEN_8_SPECIES + 60
#define SPECIES_FALINKS 		GEN_8_SPECIES + 61
#define SPECIES_PINCURCHIN 		GEN_8_SPECIES + 62
#define SPECIES_SNOM 			GEN_8_SPECIES + 63
#define SPECIES_FROSMOTH 		GEN_8_SPECIES + 64
#define SPECIES_STONJOURNER 	GEN_8_SPECIES + 65
#define SPECIES_EISCUE 			GEN_8_SPECIES + 66
#define SPECIES_INDEEDEE 		GEN_8_SPECIES + 67
#define SPECIES_MORPEKO 		GEN_8_SPECIES + 68
#define SPECIES_CUFANT 			GEN_8_SPECIES + 69
#define SPECIES_COPPERAJAH 		GEN_8_SPECIES + 70
#define SPECIES_DRACOZOLT 		GEN_8_SPECIES + 71
#define SPECIES_ARCTOZOLT 		GEN_8_SPECIES + 72
#define SPECIES_DRACOVISH 		GEN_8_SPECIES + 73
#define SPECIES_ARCTOVISH 		GEN_8_SPECIES + 74
#define SPECIES_DURALUDON 		GEN_8_SPECIES + 75
#define SPECIES_DREEPY 			GEN_8_SPECIES + 76
#define SPECIES_DRAKLOAK 		GEN_8_SPECIES + 77
#define SPECIES_DRAGAPULT 		GEN_8_SPECIES + 78
#define SPECIES_ZACIAN 			GEN_8_SPECIES + 79
#define SPECIES_ZAMAZENTA 		GEN_8_SPECIES + 80
#define SPECIES_ETERNATUS 		GEN_8_SPECIES + 81
#define SPECIES_KUBFU 			GEN_8_SPECIES + 82
#define SPECIES_URSHIFU 		GEN_8_SPECIES + 83
#define SPECIES_ZARUDE 			GEN_8_SPECIES + 84
#define SPECIES_REGIELEKI 		GEN_8_SPECIES + 85
#define SPECIES_REGIDRAGO 		GEN_8_SPECIES + 86
#define SPECIES_GLASTRIER 		GEN_8_SPECIES + 87
#define SPECIES_SPECTRIER 		GEN_8_SPECIES + 88
#define SPECIES_CALYREX 		GEN_8_SPECIES + 89

#define FORMS_START SPECIES_CALYREX

// Megas
#define SPECIES_VENUSAUR_MEGA                FORMS_START + 1
#define SPECIES_CHARIZARD_MEGA_X             FORMS_START + 2
#define SPECIES_CHARIZARD_MEGA_Y             FORMS_START + 3
#define SPECIES_BLASTOISE_MEGA               FORMS_START + 4
#define SPECIES_BEEDRILL_MEGA                FORMS_START + 5
#define SPECIES_PIDGEOT_MEGA                 FORMS_START + 6
#define SPECIES_ALAKAZAM_MEGA                FORMS_START + 7
#define SPECIES_SLOWBRO_MEGA                 FORMS_START + 8
#define SPECIES_GENGAR_MEGA                  FORMS_START + 9
#define SPECIES_KANGASKHAN_MEGA              FORMS_START + 10
#define SPECIES_PINSIR_MEGA                  FORMS_START + 11
#define SPECIES_GYARADOS_MEGA                FORMS_START + 12
#define SPECIES_AERODACTYL_MEGA              FORMS_START + 13
#define SPECIES_MEWTWO_MEGA_X                FORMS_START + 14
#define SPECIES_MEWTWO_MEGA_Y                FORMS_START + 15
#define SPECIES_AMPHAROS_MEGA                FORMS_START + 16
#define SPECIES_STEELIX_MEGA                 FORMS_START + 17
#define SPECIES_SCIZOR_MEGA                  FORMS_START + 18
#define SPECIES_HERACROSS_MEGA               FORMS_START + 19
#define SPECIES_HOUNDOOM_MEGA                FORMS_START + 20
#define SPECIES_TYRANITAR_MEGA               FORMS_START + 21
#define SPECIES_SCEPTILE_MEGA                FORMS_START + 22
#define SPECIES_BLAZIKEN_MEGA                FORMS_START + 23
#define SPECIES_SWAMPERT_MEGA                FORMS_START + 24
#define SPECIES_GARDEVOIR_MEGA               FORMS_START + 25
#define SPECIES_SABLEYE_MEGA                 FORMS_START + 26
#define SPECIES_MAWILE_MEGA                  FORMS_START + 27
#define SPECIES_AGGRON_MEGA                  FORMS_START + 28
#define SPECIES_MEDICHAM_MEGA                FORMS_START + 29
#define SPECIES_MANECTRIC_MEGA               FORMS_START + 30
#define SPECIES_SHARPEDO_MEGA                FORMS_START + 31
#define SPECIES_CAMERUPT_MEGA                FORMS_START + 32
#define SPECIES_ALTARIA_MEGA                 FORMS_START + 33
#define SPECIES_BANETTE_MEGA                 FORMS_START + 34
#define SPECIES_ABSOL_MEGA                   FORMS_START + 35
#define SPECIES_GLALIE_MEGA                  FORMS_START + 36
#define SPECIES_SALAMENCE_MEGA               FORMS_START + 37
#define SPECIES_METAGROSS_MEGA               FORMS_START + 38
#define SPECIES_LATIAS_MEGA                  FORMS_START + 39
#define SPECIES_LATIOS_MEGA                  FORMS_START + 40
#define SPECIES_LOPUNNY_MEGA                 FORMS_START + 41
#define SPECIES_GARCHOMP_MEGA                FORMS_START + 42
#define SPECIES_LUCARIO_MEGA                 FORMS_START + 43
#define SPECIES_ABOMASNOW_MEGA               FORMS_START + 44
#define SPECIES_GALLADE_MEGA                 FORMS_START + 45
#define SPECIES_AUDINO_MEGA                  FORMS_START + 46
#define SPECIES_DIANCIE_MEGA                 FORMS_START + 47

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA                FORMS_START + 48
#define SPECIES_KYOGRE_PRIMAL                FORMS_START + 49
#define SPECIES_GROUDON_PRIMAL               FORMS_START + 50

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN               FORMS_START + 51
#define SPECIES_RATICATE_ALOLAN              FORMS_START + 52
#define SPECIES_RAICHU_ALOLAN                FORMS_START + 53
#define SPECIES_SANDSHREW_ALOLAN             FORMS_START + 54
#define SPECIES_SANDSLASH_ALOLAN             FORMS_START + 55
#define SPECIES_VULPIX_ALOLAN                FORMS_START + 56
#define SPECIES_NINETALES_ALOLAN             FORMS_START + 57
#define SPECIES_DIGLETT_ALOLAN               FORMS_START + 58
#define SPECIES_DUGTRIO_ALOLAN               FORMS_START + 59
#define SPECIES_MEOWTH_ALOLAN                FORMS_START + 60
#define SPECIES_PERSIAN_ALOLAN               FORMS_START + 61
#define SPECIES_GEODUDE_ALOLAN               FORMS_START + 62
#define SPECIES_GRAVELER_ALOLAN              FORMS_START + 63
#define SPECIES_GOLEM_ALOLAN                 FORMS_START + 64
#define SPECIES_GRIMER_ALOLAN                FORMS_START + 65
#define SPECIES_MUK_ALOLAN                   FORMS_START + 66
#define SPECIES_EXEGGUTOR_ALOLAN             FORMS_START + 67
#define SPECIES_MAROWAK_ALOLAN               FORMS_START + 68

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN              FORMS_START + 69
#define SPECIES_PONYTA_GALARIAN              FORMS_START + 70
#define SPECIES_RAPIDASH_GALARIAN            FORMS_START + 71
#define SPECIES_SLOWPOKE_GALARIAN            FORMS_START + 72
#define SPECIES_SLOWBRO_GALARIAN             FORMS_START + 73
#define SPECIES_FARFETCHD_GALARIAN           FORMS_START + 74
#define SPECIES_WEEZING_GALARIAN             FORMS_START + 75
#define SPECIES_MR_MIME_GALARIAN             FORMS_START + 76
#define SPECIES_ARTICUNO_GALARIAN            FORMS_START + 77
#define SPECIES_ZAPDOS_GALARIAN              FORMS_START + 78
#define SPECIES_MOLTRES_GALARIAN             FORMS_START + 79
#define SPECIES_SLOWKING_GALARIAN            FORMS_START + 80
#define SPECIES_CORSOLA_GALARIAN             FORMS_START + 81
#define SPECIES_ZIGZAGOON_GALARIAN           FORMS_START + 82
#define SPECIES_LINOONE_GALARIAN             FORMS_START + 83
#define SPECIES_DARUMAKA_GALARIAN            FORMS_START + 84
#define SPECIES_DARMANITAN_GALARIAN          FORMS_START + 85
#define SPECIES_YAMASK_GALARIAN              FORMS_START + 86
#define SPECIES_STUNFISK_GALARIAN            FORMS_START + 87

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY              FORMS_START + 88
#define SPECIES_PIKACHU_ROCK_STAR            FORMS_START + 89
#define SPECIES_PIKACHU_BELLE                FORMS_START + 90
#define SPECIES_PIKACHU_POP_STAR             FORMS_START + 91
#define SPECIES_PIKACHU_PH_D                 FORMS_START + 92
#define SPECIES_PIKACHU_LIBRE                FORMS_START + 93

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP         FORMS_START + 94
#define SPECIES_PIKACHU_HOENN_CAP            FORMS_START + 95
#define SPECIES_PIKACHU_SINNOH_CAP           FORMS_START + 96
#define SPECIES_PIKACHU_UNOVA_CAP            FORMS_START + 97
#define SPECIES_PIKACHU_KALOS_CAP            FORMS_START + 98
#define SPECIES_PIKACHU_ALOLA_CAP            FORMS_START + 99
#define SPECIES_PIKACHU_PARTNER_CAP          FORMS_START + 100
#define SPECIES_PIKACHU_WORLD_CAP            FORMS_START + 101

// Pichu
#define SPECIES_PICHU_SPIKY_EARED            FORMS_START + 102

// Unown
#define SPECIES_UNOWN_B                      FORMS_START + 103
#define SPECIES_UNOWN_C                      FORMS_START + 104
#define SPECIES_UNOWN_D                      FORMS_START + 105
#define SPECIES_UNOWN_E                      FORMS_START + 106
#define SPECIES_UNOWN_F                      FORMS_START + 107
#define SPECIES_UNOWN_G                      FORMS_START + 108
#define SPECIES_UNOWN_H                      FORMS_START + 109
#define SPECIES_UNOWN_I                      FORMS_START + 110
#define SPECIES_UNOWN_J                      FORMS_START + 111
#define SPECIES_UNOWN_K                      FORMS_START + 112
#define SPECIES_UNOWN_L                      FORMS_START + 113
#define SPECIES_UNOWN_M                      FORMS_START + 114
#define SPECIES_UNOWN_N                      FORMS_START + 115
#define SPECIES_UNOWN_O                      FORMS_START + 116
#define SPECIES_UNOWN_P                      FORMS_START + 117
#define SPECIES_UNOWN_Q                      FORMS_START + 118
#define SPECIES_UNOWN_R                      FORMS_START + 119
#define SPECIES_UNOWN_S                      FORMS_START + 120
#define SPECIES_UNOWN_T                      FORMS_START + 121
#define SPECIES_UNOWN_U                      FORMS_START + 122
#define SPECIES_UNOWN_V                      FORMS_START + 123
#define SPECIES_UNOWN_W                      FORMS_START + 124
#define SPECIES_UNOWN_X                      FORMS_START + 125
#define SPECIES_UNOWN_Y                      FORMS_START + 126
#define SPECIES_UNOWN_Z                      FORMS_START + 127
#define SPECIES_UNOWN_EMARK                  FORMS_START + 128
#define SPECIES_UNOWN_QMARK                  FORMS_START + 129

// Castform
#define SPECIES_CASTFORM_SUNNY               FORMS_START + 130
#define SPECIES_CASTFORM_RAINY               FORMS_START + 131
#define SPECIES_CASTFORM_SNOWY               FORMS_START + 132

// Deoxys
#define SPECIES_DEOXYS_ATTACK                FORMS_START + 133
#define SPECIES_DEOXYS_DEFENSE               FORMS_START + 134
#define SPECIES_DEOXYS_SPEED                 FORMS_START + 135

// Burmy
#define SPECIES_BURMY_SANDY_CLOAK            FORMS_START + 136
#define SPECIES_BURMY_TRASH_CLOAK            FORMS_START + 137

// Wormadam
#define SPECIES_WORMADAM_SANDY_CLOAK         FORMS_START + 138
#define SPECIES_WORMADAM_TRASH_CLOAK         FORMS_START + 139

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE             FORMS_START + 140

// Shellos
#define SPECIES_SHELLOS_EAST_SEA             FORMS_START + 141

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA           FORMS_START + 142

// Rotom
#define SPECIES_ROTOM_HEAT                   FORMS_START + 143
#define SPECIES_ROTOM_WASH                   FORMS_START + 144
#define SPECIES_ROTOM_FROST                  FORMS_START + 145
#define SPECIES_ROTOM_FAN                    FORMS_START + 146
#define SPECIES_ROTOM_MOW                    FORMS_START + 147

// Giratina
#define SPECIES_GIRATINA_ORIGIN              FORMS_START + 148

// Shaymin
#define SPECIES_SHAYMIN_SKY                  FORMS_START + 149

// Arceus
#define SPECIES_ARCEUS_FIGHTING              FORMS_START + 150
#define SPECIES_ARCEUS_FLYING                FORMS_START + 151
#define SPECIES_ARCEUS_POISON                FORMS_START + 152
#define SPECIES_ARCEUS_GROUND                FORMS_START + 153
#define SPECIES_ARCEUS_ROCK                  FORMS_START + 154
#define SPECIES_ARCEUS_BUG                   FORMS_START + 155
#define SPECIES_ARCEUS_GHOST                 FORMS_START + 156
#define SPECIES_ARCEUS_STEEL                 FORMS_START + 157
#define SPECIES_ARCEUS_FIRE                  FORMS_START + 158
#define SPECIES_ARCEUS_WATER                 FORMS_START + 159
#define SPECIES_ARCEUS_GRASS                 FORMS_START + 160
#define SPECIES_ARCEUS_ELECTRIC              FORMS_START + 161
#define SPECIES_ARCEUS_PSYCHIC               FORMS_START + 162
#define SPECIES_ARCEUS_ICE                   FORMS_START + 163
#define SPECIES_ARCEUS_DRAGON                FORMS_START + 164
#define SPECIES_ARCEUS_DARK                  FORMS_START + 165
#define SPECIES_ARCEUS_FAIRY                 FORMS_START + 166

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED        FORMS_START + 167

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE          FORMS_START + 168
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 169

// Deerling
#define SPECIES_DEERLING_SUMMER              FORMS_START + 170
#define SPECIES_DEERLING_AUTUMN              FORMS_START + 171
#define SPECIES_DEERLING_WINTER              FORMS_START + 172

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER              FORMS_START + 173
#define SPECIES_SAWSBUCK_AUTUMN              FORMS_START + 174
#define SPECIES_SAWSBUCK_WINTER              FORMS_START + 175

// Therian Forms
#define SPECIES_TORNADUS_THERIAN             FORMS_START + 176
#define SPECIES_THUNDURUS_THERIAN            FORMS_START + 177
#define SPECIES_LANDORUS_THERIAN             FORMS_START + 178

// Kyurem
#define SPECIES_KYUREM_WHITE                 FORMS_START + 179
#define SPECIES_KYUREM_BLACK                 FORMS_START + 180

// Keldeo
#define SPECIES_KELDEO_RESOLUTE              FORMS_START + 181

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE           FORMS_START + 182

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE         FORMS_START + 183
#define SPECIES_GENESECT_SHOCK_DRIVE         FORMS_START + 184
#define SPECIES_GENESECT_BURN_DRIVE          FORMS_START + 185
#define SPECIES_GENESECT_CHILL_DRIVE         FORMS_START + 186

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND         FORMS_START + 187
#define SPECIES_GRENINJA_ASH                 FORMS_START + 188

// Vivillon
#define SPECIES_VIVILLON_POLAR               FORMS_START + 189
#define SPECIES_VIVILLON_TUNDRA              FORMS_START + 190
#define SPECIES_VIVILLON_CONTINENTAL         FORMS_START + 191
#define SPECIES_VIVILLON_GARDEN              FORMS_START + 192
#define SPECIES_VIVILLON_ELEGANT             FORMS_START + 193
#define SPECIES_VIVILLON_MEADOW              FORMS_START + 194
#define SPECIES_VIVILLON_MODERN              FORMS_START + 195
#define SPECIES_VIVILLON_MARINE              FORMS_START + 196
#define SPECIES_VIVILLON_ARCHIPELAGO         FORMS_START + 197
#define SPECIES_VIVILLON_HIGH_PLAINS         FORMS_START + 198
#define SPECIES_VIVILLON_SANDSTORM           FORMS_START + 199
#define SPECIES_VIVILLON_RIVER               FORMS_START + 200
#define SPECIES_VIVILLON_MONSOON             FORMS_START + 201
#define SPECIES_VIVILLON_SAVANNA             FORMS_START + 202
#define SPECIES_VIVILLON_SUN                 FORMS_START + 203
#define SPECIES_VIVILLON_OCEAN               FORMS_START + 204
#define SPECIES_VIVILLON_JUNGLE              FORMS_START + 205
#define SPECIES_VIVILLON_FANCY               FORMS_START + 206
#define SPECIES_VIVILLON_POKE_BALL           FORMS_START + 207

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER        FORMS_START + 208
#define SPECIES_FLABEBE_ORANGE_FLOWER        FORMS_START + 209
#define SPECIES_FLABEBE_BLUE_FLOWER          FORMS_START + 210
#define SPECIES_FLABEBE_WHITE_FLOWER         FORMS_START + 211

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER        FORMS_START + 212
#define SPECIES_FLOETTE_ORANGE_FLOWER        FORMS_START + 213
#define SPECIES_FLOETTE_BLUE_FLOWER          FORMS_START + 214
#define SPECIES_FLOETTE_WHITE_FLOWER         FORMS_START + 215
#define SPECIES_FLOETTE_ETERNAL_FLOWER       FORMS_START + 216

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER        FORMS_START + 217
#define SPECIES_FLORGES_ORANGE_FLOWER        FORMS_START + 218
#define SPECIES_FLORGES_BLUE_FLOWER          FORMS_START + 219
#define SPECIES_FLORGES_WHITE_FLOWER         FORMS_START + 220

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM           FORMS_START + 221
#define SPECIES_FURFROU_STAR_TRIM            FORMS_START + 222
#define SPECIES_FURFROU_DIAMOND_TRIM         FORMS_START + 223
#define SPECIES_FURFROU_DEBUTANTE_TRIM       FORMS_START + 224
#define SPECIES_FURFROU_MATRON_TRIM          FORMS_START + 225
#define SPECIES_FURFROU_DANDY_TRIM           FORMS_START + 226
#define SPECIES_FURFROU_LA_REINE_TRIM        FORMS_START + 227
#define SPECIES_FURFROU_KABUKI_TRIM          FORMS_START + 228
#define SPECIES_FURFROU_PHARAOH_TRIM         FORMS_START + 229

// Meowstic
#define SPECIES_MEOWSTIC_FEMALE              FORMS_START + 230

// Aegislash
#define SPECIES_AEGISLASH_BLADE              FORMS_START + 231

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL              FORMS_START + 232
#define SPECIES_PUMPKABOO_LARGE              FORMS_START + 233
#define SPECIES_PUMPKABOO_SUPER              FORMS_START + 234

// Gourgeist
#define SPECIES_GOURGEIST_SMALL              FORMS_START + 235
#define SPECIES_GOURGEIST_LARGE              FORMS_START + 236
#define SPECIES_GOURGEIST_SUPER              FORMS_START + 237

// Xerneas
#define SPECIES_XERNEAS_ACTIVE               FORMS_START + 238

// Zygarde
#define SPECIES_ZYGARDE_10                   FORMS_START + 239
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT   FORMS_START + 240
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT   FORMS_START + 241
#define SPECIES_ZYGARDE_COMPLETE             FORMS_START + 242

// Hoopa
#define SPECIES_HOOPA_UNBOUND                FORMS_START + 243

// Oricorio
#define SPECIES_ORICORIO_POM_POM             FORMS_START + 244
#define SPECIES_ORICORIO_PAU                 FORMS_START + 245
#define SPECIES_ORICORIO_SENSU               FORMS_START + 246

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO           FORMS_START + 247

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT            FORMS_START + 248
#define SPECIES_LYCANROC_DUSK                FORMS_START + 249

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL            FORMS_START + 250

// Silvally
#define SPECIES_SILVALLY_FIGHTING            FORMS_START + 251
#define SPECIES_SILVALLY_FLYING              FORMS_START + 252
#define SPECIES_SILVALLY_POISON              FORMS_START + 253
#define SPECIES_SILVALLY_GROUND              FORMS_START + 254
#define SPECIES_SILVALLY_ROCK                FORMS_START + 255
#define SPECIES_SILVALLY_BUG                 FORMS_START + 256
#define SPECIES_SILVALLY_GHOST               FORMS_START + 257
#define SPECIES_SILVALLY_STEEL               FORMS_START + 258
#define SPECIES_SILVALLY_FIRE                FORMS_START + 259
#define SPECIES_SILVALLY_WATER               FORMS_START + 260
#define SPECIES_SILVALLY_GRASS               FORMS_START + 261
#define SPECIES_SILVALLY_ELECTRIC            FORMS_START + 262
#define SPECIES_SILVALLY_PSYCHIC             FORMS_START + 263
#define SPECIES_SILVALLY_ICE                 FORMS_START + 264
#define SPECIES_SILVALLY_DRAGON              FORMS_START + 265
#define SPECIES_SILVALLY_DARK                FORMS_START + 266
#define SPECIES_SILVALLY_FAIRY               FORMS_START + 267

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE         FORMS_START + 268
#define SPECIES_MINIOR_METEOR_YELLOW         FORMS_START + 269
#define SPECIES_MINIOR_METEOR_GREEN          FORMS_START + 270
#define SPECIES_MINIOR_METEOR_BLUE           FORMS_START + 271
#define SPECIES_MINIOR_METEOR_INDIGO         FORMS_START + 272
#define SPECIES_MINIOR_METEOR_VIOLET         FORMS_START + 273
#define SPECIES_MINIOR_CORE_RED              FORMS_START + 274
#define SPECIES_MINIOR_CORE_ORANGE           FORMS_START + 275
#define SPECIES_MINIOR_CORE_YELLOW           FORMS_START + 276
#define SPECIES_MINIOR_CORE_GREEN            FORMS_START + 277
#define SPECIES_MINIOR_CORE_BLUE             FORMS_START + 278
#define SPECIES_MINIOR_CORE_INDIGO           FORMS_START + 279
#define SPECIES_MINIOR_CORE_VIOLET           FORMS_START + 280

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED               FORMS_START + 281

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE           FORMS_START + 282
#define SPECIES_NECROZMA_DAWN_WINGS          FORMS_START + 283
#define SPECIES_NECROZMA_ULTRA               FORMS_START + 284

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR      FORMS_START + 285

// Cramorant
#define SPECIES_CRAMORANT_GULPING            FORMS_START + 286
#define SPECIES_CRAMORANT_GORGING            FORMS_START + 287

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY           FORMS_START + 288

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE             FORMS_START + 289

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE          FORMS_START + 290

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM          FORMS_START + 291
#define SPECIES_ALCREMIE_MATCHA_CREAM        FORMS_START + 292
#define SPECIES_ALCREMIE_MINT_CREAM          FORMS_START + 293
#define SPECIES_ALCREMIE_LEMON_CREAM         FORMS_START + 294
#define SPECIES_ALCREMIE_SALTED_CREAM        FORMS_START + 295
#define SPECIES_ALCREMIE_RUBY_SWIRL          FORMS_START + 296
#define SPECIES_ALCREMIE_CARAMEL_SWIRL       FORMS_START + 297
#define SPECIES_ALCREMIE_RAINBOW_SWIRL       FORMS_START + 298

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE            FORMS_START + 299

// Indeedee
#define SPECIES_INDEEDEE_FEMALE              FORMS_START + 300

// Morpeko
#define SPECIES_MORPEKO_HANGRY               FORMS_START + 301

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD         FORMS_START + 302

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD     FORMS_START + 303

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX          FORMS_START + 304

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE   FORMS_START + 305

// Zarude
#define SPECIES_ZARUDE_DADA                  FORMS_START + 306

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER            FORMS_START + 307
#define SPECIES_CALYREX_SHADOW_RIDER         FORMS_START + 308

#define SPECIES_EGG SPECIES_CALYREX_SHADOW_RIDER + 1
#define NUM_SPECIES SPECIES_EGG

// Species Flags
#define FLAG_ULTRA_BEAST        (1 << 0)
#define FLAG_ALOLAN_FORM        (1 << 1)
#define FLAG_GALARIAN_FORM      (1 << 2)
#define FLAG_GENDER_DIFFERENCE  (1 << 3)

#endif  // GUARD_CONSTANTS_SPECIES_H
