gText_Birch_Welcome::
    .string "Hello, there!\n"
    .string "Glad to meet you!\p"
    .string "Welcome to the world of Pokémon!\p"
    .string "My name is Oak.\p"
    .string "People affectionately refer to me\n"
    .string "as the Pokémon Professor.\p"
    .string "$"

gText_Birch_Pokemon::
	.string "This world…\p"
	.string "$"

gText_Birch_MainSpeech::
    .string "…is inhabited far and wide by\n"
    .string "creatures called Pokémon.\p"
    .string "For some people, Pokémon are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study Pokémon as a profession,\n"
    .string "and often collaborate with other\l"
    .string "researchers around the world.\p"
    .string "In fact, one of my colleagues\n"
    .string "has a lab in your new hometown.\p"
    .string "$"

gText_Birch_AndYouAre::
	.string "Come to think of it, Professor\n"
	.string "Birch has a child that helps him\l"
	.string "with his fieldwork.$"

gText_Birch_BoyOrGirl::
	.string "Err...\n"
	.string "What was their name again?$"

gText_Birch_WhatsYourName::
	.string "Ah, thats right.\p"
	.string "Now, what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\p$"

gText_Birch_YourePlayer::
	.string "Excellent!\p$"

gText_Birch_AreYouReady::
    .string "{PLAYER}!\p"
    .string "Your very own Pokémon legend is\n"
    .string "about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with Pokémon awaits! Let's go!\p"
    .string "$"
