EventScript_CostumeSwap_Enby::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, ENBY_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Brendan::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, BRENDAN_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_May::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, MAY_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Red::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, RED_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Leaf::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, LEAF_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Ethan::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, ETHAN_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Lyra::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, LYRA_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Kris::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, KRIS_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Lucas::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, LUCAS_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_Dawn::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, DAWN_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_LucasPlatinum::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, LUCAS_PLATINUM_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end

EventScript_CostumeSwap_DawnPlatinum::
	lockall
	fadescreen FADE_TO_BLACK
	setvar VAR_TEMP_1, DAWN_PLATINUM_COSTUME
	special SwapPlayersCostume
	fadescreen FADE_FROM_BLACK
	releaseall
	end
